---
# ServiceAccount for GitHub Actions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-deployer
  namespace: demo

---
# ClusterRole with deployment permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-actions-deployer
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments", "replicasets", "pods", "services", "configmaps", "secrets", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# Bind ClusterRole to ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-deployer
subjects:
  - kind: ServiceAccount
    name: github-actions-deployer
    namespace: demo
roleRef:
  kind: ClusterRole
  name: github-actions-deployer
  apiGroup: rbac.authorization.k8s.io

---
# Secret for ServiceAccount token
apiVersion: v1
kind: Secret
metadata:
  name: github-actions-deployer-token
  namespace: demo
  annotations:
    kubernetes.io/service-account.name: github-actions-deployer
type: kubernetes.io/service-account-token
