#!/bin/bash

# Setup runner - version đơn giản nhất

echo "════════════════════════════════════════════════════════"
echo "  GitHub Actions Runner Setup - MANUAL GUIDE"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Hãy làm theo TỪNG BƯỚC sau đây:"
echo ""
echo "────────────────────────────────────────────────────────"
echo "BƯỚC 1: Mở browser"
echo "────────────────────────────────────────────────────────"
echo ""
echo "URL: https://github.com/datnd35/demo-ci-cd/settings/actions/runners/new"
echo ""
echo "- Click chọn: macOS"
echo "- Dropdown Architecture → chọn: ARM64"
echo ""
read -p "Nhấn Enter khi đã mở browser và chọn ARM64... "
echo ""

echo "────────────────────────────────────────────────────────"
echo "BƯỚC 2: Chạy lệnh 1 - Tạo thư mục"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Từ GitHub, tìm dòng:"
echo '  $ mkdir actions-runner && cd actions-runner'
echo ""
echo "Copy phần: mkdir actions-runner && cd actions-runner"
echo ""
echo "Chạy lệnh này trong terminal:"
echo ""
echo "mkdir actions-runner && cd actions-runner"
echo ""
read -p "Nhấn Enter khi đã chạy xong lệnh trên... "
echo ""

echo "────────────────────────────────────────────────────────"
echo "BƯỚC 3: Chạy lệnh 2 - Download"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Từ GitHub, copy TOÀN BỘ lệnh curl (rất dài)"
echo ""
echo "Dạng: curl -o actions-runner-osx-arm64-2.329.0.tar.gz -L https://..."
echo ""
echo "Copy và chạy lệnh đó trong terminal (đang ở thư mục actions-runner)"
echo ""
read -p "Nhấn Enter khi đã download xong... "
echo ""

echo "────────────────────────────────────────────────────────"
echo "BƯỚC 4: Chạy lệnh 3 - Extract"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Từ GitHub, copy lệnh tar"
echo ""
echo "Dạng: tar xzf ./actions-runner-osx-arm64-2.329.0.tar.gz"
echo ""
echo "Copy và chạy lệnh đó"
echo ""
read -p "Nhấn Enter khi đã extract xong... "
echo ""

echo "────────────────────────────────────────────────────────"
echo "BƯỚC 5: Chạy lệnh 4 - Configure (QUAN TRỌNG!)"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Từ GitHub, kéo xuống phần 'Configure'"
echo "Copy lệnh ./config.sh (có TOKEN rất dài)"
echo ""
echo "Dạng: ./config.sh --url https://github.com/datnd35/demo-ci-cd --token AXXXXXX..."
echo ""
echo "⚠️  Token chỉ có hiệu lực 1 giờ!"
echo ""
echo "Copy và chạy lệnh đó"
echo ""
read -p "Nhấn Enter khi đã configure xong... "
echo ""

echo "────────────────────────────────────────────────────────"
echo "BƯỚC 6: Start Runner"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Trong terminal đang ở thư mục ~/actions-runner, chạy:"
echo ""
echo "./run.sh"
echo ""
echo "Khi thấy 'Listening for Jobs' → Thành công!"
echo ""
echo "⚠️  Giữ terminal đó chạy, không tắt!"
echo ""
echo "════════════════════════════════════════════════════════"
echo "  DONE!"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Workflow trên GitHub sẽ tự động chạy ngay!"
echo "Xem tại: https://github.com/datnd35/demo-ci-cd/actions"
echo ""
