#!/bin/bash

# Hướng dẫn setup GitHub Self-Hosted Runner từ terminal

echo "🔧 GitHub Self-Hosted Runner Setup"
echo "===================================="
echo ""
echo "⚠️  LƯU Ý: Bạn PHẢI lấy commands từ GitHub, không thể dùng commands mẫu!"
echo ""
echo "Bước 1: Mở browser"
echo "-----------------"
echo "URL: https://github.com/datnd35/demo-ci-cd/settings/actions/runners/new"
echo ""
echo "Bước 2: Chọn macOS"
echo "------------------"
echo ""
echo "Bước 3: Copy TỪNG LỆNH MỘT từ GitHub"
echo "------------------------------------"
echo ""
echo "GitHub sẽ hiển thị các lệnh dạng như sau:"
echo ""
echo "┌─────────────────────────────────────────────────────────┐"
echo "│ Download                                                 │"
echo "├─────────────────────────────────────────────────────────┤"
echo "│ # Create a folder                                        │"
echo "│ $ mkdir actions-runner && cd actions-runner              │"
echo "│                                                          │"
echo "│ # Download the latest runner package                    │"
echo "│ $ curl -o actions-runner-osx-arm64-2.311.0.tar.gz...    │"
echo "│                                                          │"
echo "│ # Extract the installer                                 │"
echo "│ $ tar xzf ./actions-runner-osx-arm64-2.311.0.tar.gz     │"
echo "└─────────────────────────────────────────────────────────┘"
echo ""
echo "┌─────────────────────────────────────────────────────────┐"
echo "│ Configure                                                │"
echo "├─────────────────────────────────────────────────────────┤"
echo "│ # Create the runner and start the configuration...      │"
echo "│ $ ./config.sh --url https://github.com/datnd35/...      │"
echo "│                                                          │"
echo "│ # Last step, run it!                                    │"
echo "│ $ ./run.sh                                              │"
echo "└─────────────────────────────────────────────────────────┘"
echo ""
echo "⚠️  CHỈ COPY PHẦN SAU DẤU $, KHÔNG COPY DẤU $ VÀ # !"
echo ""
echo "Ví dụ copy đúng:"
echo "  mkdir actions-runner && cd actions-runner"
echo ""
echo "Ví dụ copy SAI:"
echo "  $ mkdir actions-runner && cd actions-runner"
echo "  # Create a folder"
echo ""
echo ""
read -p "Bạn đã mở browser và thấy commands từ GitHub chưa? (y/n): " answer

if [ "$answer" != "y" ]; then
    echo ""
    echo "Hãy mở browser và vào link:"
    echo "https://github.com/datnd35/demo-ci-cd/settings/actions/runners/new"
    echo ""
    echo "Sau đó chạy lại script này!"
    exit 1
fi

echo ""
echo "✅ Tuyệt vời! Bây giờ hãy:"
echo ""
echo "1. Copy lệnh THỨ NHẤT từ GitHub (mkdir actions-runner...)"
echo "2. Paste vào terminal và Enter"
echo "3. Copy lệnh THỨ HAI từ GitHub (curl -o...)"
echo "4. Paste và Enter"
echo "5. Tiếp tục với các lệnh còn lại"
echo ""
echo "Sau khi runner đã chạy (./run.sh), quay lại terminal này!"
echo ""
